### PR TITLE
correct python version for RTD

### LINKED ISSUE #39: Doc Build failing due to non-specific python version in readthedocs.yaml
title explains it.

### PR DESCRIPTION
**Pull request by askpatrickw**
fixes #39

### CODE REVIEW

**Comment by dhalbert** [comment]
Let's figure out if we can avoid doing this in some way, because we changed a lot of libraries, and it would be better not to have to update this each time we want to bump versions.

**Comment by FoamyGuy** [comment]
The RTD error page indicates some other possible versions:

including `3`. Perhaps that would behave as wanted 3.x to?
image

**Comment by dhalbert** [comment]
https://github.com/readthedocs/readthedocs.org/issues/7814 says it is now possible with https://github.com/readthedocs/readthedocs.org/pull/8453. "Docs to be updated".

**Comment by dhalbert** [comment]
https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version says `python.version` is deprecated, and to use `build.tools.python` (https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python), where you can specify `"3"` as the version. 

Not "3.x", boo hoo. But we'd change to
```yaml
build:
  tools:
    python: "3"
```
anyway: https://docs.readthedocs.io/en/stable/config-file/v2.html#build

Could you try that? Thanks.

**Review by dhalbert — CHANGES_REQUESTED** [review]
see posts

**Review by FoamyGuy — APPROVED** [review]
LGTM, matches recent change merged in cookiecutter repo.

**Pull request merged**
