### PR TITLE
CPSockets Updates

### LINKED ISSUE #24: CPython sockets compatibility
A typical setup requires an  esp object which is related to the ESP32 wifi add-on boards.

`device = IoTCentralDevice(socket, esp, secrets["id_scope"], secrets["device_id"], secrets["key"])`

With the ESP32-s2 and its native wifi support, there is now a CPython-like socketpool. 
IoTCentralDevice needs to be udpated to support both methods similarly if not the same way [Requests does](https://github.com/adafruit/Adafruit_CircuitPython_Requests) and [MiniMQTT is going to be](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues).

### PR DESCRIPTION
**Pull request by askpatrickw**
will fix #24 (hopefully, someday...) 

All the IoT Hub Examples are working.

The IoT Central  examples all fail and are unable to connect. 
You can see that the device registration works, it gets back iot central's hub.
But when connecting, it fails with OSError: 23 within the try in _get_connect_socket

```python
20914.2: INFO - Establishing a SECURE SSL connection to iotc-snip-snip-snip-snip-snip.azure-devices.net:8883
Traceback (most recent call last):
  File "code.py", line 122, in <module>
  File "/lib/adafruit_azureiot/iotcentral_device.py", line 163, in connect
  File "/lib/adafruit_azureiot/iot_mqtt.py", line 387, in connect
  File "/lib/adafruit_azureiot/iot_mqtt.py", line 133, in _create_mqtt_client
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 439, in connect
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 273, in _get_connect_socket
RuntimeError: Repeated socket failures
```

I'm now wondering if the IoT Central API changed...

### CODE REVIEW

**Comment by askpatrickw** [comment]
@jimbobbennett I'm wondering if you know of a change in IoT Central that we need to sync-up to, or some other such change I'm just not aware of. tx!

**Comment by jimbobbennett** [comment]
I've done some digging, but have no idea why it's not working, and I can't see anything we're doing different to the [unofficial MS Python IoT Central SDK](https://github.com/iot-for-all/iotc-python-client). I'll follow up with the SDK team here to see if anything has changed.

**Comment by jimbobbennett** [comment]
I'm getting nowhere with this. It looks like something is different between the IoT Hubs created by IoT Central, and a standard IoT Hub created in the Azure Portal.

I tried generating the MQTT settings for the IoT Central hub using the official Azure Python SDK, and the CircuitPython library can't connect using the same settings.

I've asked around here so will update if I get more info.

**Comment by askpatrickw** [comment]
Thanks @jimbobbennett. Although frustrating, at least we both reproduced the same issue.

**Comment by askpatrickw** [comment]
Closing this PR which is now being fixed in PR  #31

**Pull request closed without merging**
