### PR TITLE
Fixed pylint failures - mostly line-too-long

### PR DESCRIPTION
**Pull request by evaherrada**
Def needs to be looked over after it is merged to make sure all the documentation still looks ok.

### CODE REVIEW

**Comment by evaherrada** [comment]
oops forgot to do the examples

**Comment by evaherrada** [comment]
Not entirely sure about this failure. Someone else may be able to fix it much quicker than me

**Comment by tekktrik** [comment]
Looks like `mpy-cross` is failing to compile the library, I'll look into this one

**Review by tekktrik — CHANGES_REQUESTED** [review]
Let's also disable the warning against `lambda` assignment here.

**Comment by tekktrik** [comment]
The issue it's having with compiling the `.mpy` files seems to be related to have f-strings on multiple lines.  I can make some suggestions after looking more into it, but honestly it'll be worth considering disabling the "line too long" warning for those lines and leaving a comment about why that was done.

**Review by tekktrik — APPROVED** [review]
Fixed remaining issues

**Pull request merged**
