### PR TITLE
Change from library dependency to code to save 37K of memory

### PR DESCRIPTION
**Pull request by jimbobbennett**
The Adafruit_hashlib library uses a lot of memory, 26K. The Azure IoT library uses the CircuitPython HMAC library, which uses this library, eating a total of 29K.

These libraries handle a number of different hashing sizes, but the Azure IoT library only needs 256. By bringing in the code for just this, we can save 18K in memory usage, which is substantial!

Also removed dependencies on Parse and Base64, importing just the bare minimum code needed.

Saves 37K in total.

### CODE REVIEW

**Comment by jimbobbennett** [comment]
I'm still testing everything works, just wanted to raise this for visibility.

**Comment by jimbobbennett** [comment]
Also removed dependencies on Parse and Base64, importing just the bare minimum code needed.

Saves 37K

**Comment by jimbobbennett** [comment]
Memory usage testing was done with this code:

```python
gc.collect()
free_memory = gc.mem_free()

from adafruit_azureiot import IoTCentralDevice

gc.collect()
print("Used memory", free_memory - gc.mem_free())
free_memory = gc.mem_free()
```

**Comment by jimbobbennett** [comment]
All tested and ready for review.

**Comment by tannewt** [comment]
Note that the gc.collect() is redundant because CircuitPython will automatically collect after every import.

**Pull request merged**
