### PR TITLE
Fix 24  CPython sockets compatibility

### LINKED ISSUE #24: CPython sockets compatibility
A typical setup requires an  esp object which is related to the ESP32 wifi add-on boards.

`device = IoTCentralDevice(socket, esp, secrets["id_scope"], secrets["device_id"], secrets["key"])`

With the ESP32-s2 and its native wifi support, there is now a CPython-like socketpool. 
IoTCentralDevice needs to be udpated to support both methods similarly if not the same way [Requests does](https://github.com/adafruit/Adafruit_CircuitPython_Requests) and [MiniMQTT is going to be](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues).

### PR DESCRIPTION
**Pull request by askpatrickw**
fixes #24 

When its completed... draft PR to track.
Suggestions welcome ;-)

### CODE REVIEW

**Comment by ladyada** [comment]
some folks are out next week, let us know when its ready to review!

**Comment by askpatrickw** [comment]
@brentru 
Here's where I'm at with the IoT Central path...

The AzureIOT.DeviceRegistration works (gives you your IoT Hub server name and uses Requests) but when the SSL connection to the IoT Hub starts, MiniMQTT keeps failing with MemoryErrors and eventually fails completely.

The MiniMQTT code is here https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L245
That logic is the same logic as in Requests. 

```
Traceback (most recent call last):
  File "code.py", line 88, in <module>
  File "/lib/adafruit_azureiot/iotcentral_device.py", line 162, in connect
  File "/lib/adafruit_azureiot/iot_mqtt.py", line 397, in connect
  File "/lib/adafruit_azureiot/iot_mqtt.py", line 142, in _create_mqtt_client
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 443, in connect
  File "/lib/adafruit_minimqtt/adafruit_minimqtt.py", line 277, in _get_connect_socket
RuntimeError: Repeated socket failures
```

I'm really stumped by why the exception is MemoryError.
Any suggestions on how to proceed or where to look next?

**Comment by askpatrickw** [comment]
@tannewt since Brent is off this week and this logic is very similar to requests, do you have any suggestions on next steps to with these MemoryErrors? I've tried this on a FeatherS2 and a MetroS2 just to be sure and get the same issue.

**Comment by tannewt** [comment]
It's not clear to me what the backtrace is for a memory error because the one you posted is RuntimeError. Where is the memory error being raised?

**Comment by tannewt** [comment]
Ah, so it's coming from `connect`. I think those are usually a result of not being able to allocate the SSL buffers from the IDF. There are likely IDF memory debugging settings that could help debug this.

**Pull request closed without merging**
