### PR TITLE
Add Adafruit Logging as a dependency

### PR DESCRIPTION
**Pull request by makermelissa**
Depends on https://github.com/adafruit/Adafruit_CircuitPython_Logging/pull/26.

### CODE REVIEW

**Comment by tekktrik** [comment]
It looks like `adafruit_logging` is disabled for PyPI.  Is the fix perhaps to use the CPython `logging` module if it's Blinka via `try`/`except`?  Or should `adafruit_logging` be set up on PyPI?

**Comment by makermelissa** [comment]
> It looks like `adafruit_logging` is disabled for PyPI. Is the fix perhaps to use the CPython `logging` module if it's Blinka via `try`/`except`? Or should `adafruit_logging` be set up on PyPI?

It should be set up in PyPI. That's why it depends on https://github.com/adafruit/Adafruit_CircuitPython_Logging/pull/26

**Comment by tekktrik** [comment]
Ohhhh, my bad!

**Comment by makermelissa** [comment]
> Ohhhh, my bad!

All good. :)

**Comment by makermelissa** [comment]
Ok, this one is ready now.

**Review by tekktrik — APPROVED** [review]
Looks good to me!

**Pull request merged**
